### ISSUE TITLE
No slow motion feature? 

### ISSUE THREAD

**Issue by ljsharp** [albemala/native_video_player#2]
The package save my day instead of the slow motion. I would like you to add slow motion feature in your package. Or is it already existing? Thanks for making this package.

**Comment by albemala** [comment]
hey there,

by slow motion you mean setting the playback speed lower than 1.0?

I saw your PR by the way - thanks for that! 
does your PR solve this problem already? or is it a different problem?

**Comment by albemala** [comment]
okay, so I'm going to close this ticket as I have implemented setting the playback speed in the latest version (1.2.0)

setting a value < 1 will play videos in slow motion
