### ISSUE TITLE
Support adding HTTP headers to network requests

### ISSUE THREAD

**Issue by mertalev** [albemala/native_video_player#23]
Firstly, *thank you so much* for developing this player! We've been looking for a player that uses PlatformView forever.

The only hiccup is that it doesn't let you add headers for e.g. authorization when the video is fetched through a network request. Would you be open to implementing support for setting custom headers? And if not, would a PR that implements this be welcome?

**Comment by albemala** [comment]
hey @mertalev , glad to hear you find this package useful. I actually have to thank you and your colleague for implementing it! I've just merged your PR and will publish a new version as soon as possible. I'll update this ticket once published. Thanks again and sorry for the late reply.

**Comment by albemala** [comment]
@mertalev I've just published v2.0 with support for HTTP headers (thanks to @shenlong-tanwen 's PR!). I'm now closing this ticket. If needed, please re-open it or open a new one. Thanks!
