### ISSUE TITLE
I want to use this plugin to play TS format videos, but I found that the video is in a black screen state

### ISSUE THREAD

**Issue by FLEasy** [albemala/native_video_player#24]
I want to use this plugin to play TS format videos, but I found that the video is in a black screen state. How can I set up support for TS format videos

**Comment by albemala** [comment]
hey @FLEasy , the TS video format is not natively supported by Android or iOS, so this library doesn't support playing these kind of videos. Sorry about that, I'd suggest looking into other packages.
