### ISSUE TITLE
how to close  log

### ISSUE THREAD

**Issue by tudosxxx** [albemala/native_video_player#7]
V/MediaPlayer-JNI(14945): getCurrentPosition: 39970 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40071 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40169 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40270 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40369 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40467 (msec)
V/MediaPlayer-JNI(14945): getCurrentPosition: 40568 (msec)

**Comment by albemala** [comment]
These logs come from the Android OS and it's not possible to remove them from the library

**Comment by tudosxxx** [comment]
> 这些日志来自 Android 操作系统，无法从库中删除它们

that's bad.

**Comment by tudosxxx** [comment]
> These logs come from the Android OS and it's not possible to remove them from the library

that's bad. 
thank you
